### ISSUE TITLE
TypeError: getBranchName is not a function

### ISSUE THREAD

**Issue by elenagarrone** [tiaanduplessis/enforce-branch-name#4]
Looks like the latest changes are breaking the code with the following error:

``` 
 stdout: 'husky - pre-push hook exited with code 1 (error)',
  stderr: 'npm WARN exec The following package was not found and will be installed: enforce-branch-name\n' +
    '/home/runner/.npm/_npx/08e9d75a37a832b2/node_modules/enforce-branch-name/index.js:4\n' +
    '  const branchName = getBranchName()\n' +
    '                     ^\n' +
    '\n' +
    'TypeError: getBranchName is not a function\n' +
    '    at module.exports (/home/runner/.npm/_npx/08e9d75a37a832b2/node_modules/enforce-branch-name/index.js:4:22)\n' +
    '    at Object.<anonymous> (/home/runner/.npm/_npx/08e9d75a37a832b2/node_modules/enforce-branch-name/cli.js:5:1)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1068:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:933:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n' +
    '    at internal/main/run_main_module.js:17:47\n' +
    "error: failed to push some refs to 'https://github.com/Legal-and-General/canopy'",
```

Fixing the version to `v1.0.1` works.

**Comment by tiaanduplessis** [comment]
@elenagarrone thank you for reporting the issue. This should be resolved in `enforce-branch-name@1.1.2`
